# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
    ]
